export const FormFieldType = {
  TXTBOX: { name: 'textbox' },
  CHBOX: { name: 'checkbox' },
  DDBOX: { name: 'dropdownbox' },
  DDBOX_MUI: { name: 'muidropdownbox' },
  MULTI_DDBOX: { name: 'multi_dropdownbox' },
  COMBOX: { name: 'combox' },
  LIST_CBOX: { name: 'listcombox' },
  LISTBOX: { name: 'listbox' },
  DATE_PICKER: { name: 'datepicker' },
  DATETIME_PICKER: { name: 'datetimepicker' },
  SWITCH: { name: 'switch' },
  MULTI_SUBFORM: { name: 'multi-subform' },
  FILE: { name: 'file' },
  CUSTOM: { name: 'custom' },
};
