name: Publish QA Standalone Docker Image

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Docker image tag'
        required: true

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - 
        name: Set tag
        run: |
          TAG=qa-testing-${{ github.event.inputs.tag }}
          echo "TAG=${TAG}" >> $GITHUB_ENV          
      - 
        name: Checkout
        uses: actions/checkout@v4
      - 
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - 
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - 
        name: Login to DockerHub
        uses: docker/login-action@v3
        with:
            username: ${{ secrets.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v6
        with:
            context: .
            file: ./Dockerfile.standalone
            platforms: linux/amd64, linux/arm64, linux/arm/v7
            push: true
            tags: ${{ github.repository_owner }}/netmaker-ui:${{ env.TAG }}
    
         

    